weights:
  layoutlmv3: Layout/LayoutLMv3/model_final.pth
  doclayout_yolo: Layout/YOLO/doclayout_yolo_ft.pt
  yolo_v8_mfd: MFD/YOLO/yolo_v8_ft.pt
  unimernet_small: MFR/unimernet_small
  struct_eqtable: TabRec/StructEqTable
  tablemaster: TabRec/TableMaster